##config
server:
    port: 8761
##单服务模式
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-register: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/