##config
server:
    port: 8761
##单服务模式
spring:
  application:
    name: ${APP_NAME:BOSS-CONFIG-SERVICE}
    instance_id: ${random.value}
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id}
    perferIpAddress: true
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-register: false
    serviceUrl:
      defaultZone: ${SERVICE_URL:http://${BOSS_EUREKA_PORT:127.0.0.1}:${SERVICE_EUREKA_PORT:8761}/${register.name:eureka}/}