##config
server:
    port: 8761

spring:
  application:
    name: ${APP_NAME:BOSS-CONFIG-SERVICE}
    instance_id: ${random.value}
  cloud:
    config:
      server:
        native:
          serach-locations: classpath:/config  
    
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id}
    perferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: default
    availabilityZones:
      default: devZone
    preferSameZone: false
    serviceUrl:
      devZone: ${SERVICE_URL:http://${BOSS_EUREKA_IP:127.0.0.1}:${BOSS_EUREKA_PORT:8761}/${register.name:eureka}/}